# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProductArgs', 'Product']

@pulumi.input_type
class ProductArgs:
    def __init__(__self__, *,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 images: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 marketing_features: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 package_dimensions: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]] = None,
                 product_id: Optional[pulumi.Input[_builtins.str]] = None,
                 shippable: Optional[pulumi.Input[_builtins.bool]] = None,
                 statement_descriptor: Optional[pulumi.Input[_builtins.str]] = None,
                 tax_code: Optional[pulumi.Input[_builtins.str]] = None,
                 unit_label: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Product resource.
        :param pulumi.Input[_builtins.bool] active: Bool. Whether the product is currently available for purchase. Defaults to `true`.
        :param pulumi.Input[_builtins.str] description: String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] images: List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] marketing_features: List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] name: String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]] package_dimensions: Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: `height`,`length`,`width` and `weight`; the precision is 2 decimal places.
        :param pulumi.Input[_builtins.str] product_id: String. The bespoke unique identifier for the object.
        :param pulumi.Input[_builtins.bool] shippable: Bool. Whether this product is shipped (i.e., physical goods).
        :param pulumi.Input[_builtins.str] statement_descriptor: String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`,` >`, `\\`, `"`, `’` characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
        :param pulumi.Input[_builtins.str] tax_code: String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
        :param pulumi.Input[_builtins.str] unit_label: String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
        :param pulumi.Input[_builtins.str] url: String. A URL of a publicly-accessible webpage for this product.
        """
        if active is not None:
            pulumi.set(__self__, "active", active)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if images is not None:
            pulumi.set(__self__, "images", images)
        if marketing_features is not None:
            pulumi.set(__self__, "marketing_features", marketing_features)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if package_dimensions is not None:
            pulumi.set(__self__, "package_dimensions", package_dimensions)
        if product_id is not None:
            pulumi.set(__self__, "product_id", product_id)
        if shippable is not None:
            pulumi.set(__self__, "shippable", shippable)
        if statement_descriptor is not None:
            pulumi.set(__self__, "statement_descriptor", statement_descriptor)
        if tax_code is not None:
            pulumi.set(__self__, "tax_code", tax_code)
        if unit_label is not None:
            pulumi.set(__self__, "unit_label", unit_label)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def active(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Whether the product is currently available for purchase. Defaults to `true`.
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def images(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        """
        return pulumi.get(self, "images")

    @images.setter
    def images(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "images", value)

    @_builtins.property
    @pulumi.getter(name="marketingFeatures")
    def marketing_features(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
        """
        return pulumi.get(self, "marketing_features")

    @marketing_features.setter
    def marketing_features(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "marketing_features", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="packageDimensions")
    def package_dimensions(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]]:
        """
        Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: `height`,`length`,`width` and `weight`; the precision is 2 decimal places.
        """
        return pulumi.get(self, "package_dimensions")

    @package_dimensions.setter
    def package_dimensions(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "package_dimensions", value)

    @_builtins.property
    @pulumi.getter(name="productId")
    def product_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The bespoke unique identifier for the object.
        """
        return pulumi.get(self, "product_id")

    @product_id.setter
    def product_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "product_id", value)

    @_builtins.property
    @pulumi.getter
    def shippable(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Whether this product is shipped (i.e., physical goods).
        """
        return pulumi.get(self, "shippable")

    @shippable.setter
    def shippable(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "shippable", value)

    @_builtins.property
    @pulumi.getter(name="statementDescriptor")
    def statement_descriptor(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`,` >`, `\\`, `"`, `’` characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
        """
        return pulumi.get(self, "statement_descriptor")

    @statement_descriptor.setter
    def statement_descriptor(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "statement_descriptor", value)

    @_builtins.property
    @pulumi.getter(name="taxCode")
    def tax_code(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
        """
        return pulumi.get(self, "tax_code")

    @tax_code.setter
    def tax_code(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tax_code", value)

    @_builtins.property
    @pulumi.getter(name="unitLabel")
    def unit_label(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
        """
        return pulumi.get(self, "unit_label")

    @unit_label.setter
    def unit_label(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "unit_label", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. A URL of a publicly-accessible webpage for this product.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


@pulumi.input_type
class _ProductState:
    def __init__(__self__, *,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 images: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 marketing_features: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 package_dimensions: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]] = None,
                 product_id: Optional[pulumi.Input[_builtins.str]] = None,
                 shippable: Optional[pulumi.Input[_builtins.bool]] = None,
                 statement_descriptor: Optional[pulumi.Input[_builtins.str]] = None,
                 tax_code: Optional[pulumi.Input[_builtins.str]] = None,
                 unit_label: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Product resources.
        :param pulumi.Input[_builtins.bool] active: Bool. Whether the product is currently available for purchase. Defaults to `true`.
        :param pulumi.Input[_builtins.str] description: String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] images: List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] marketing_features: List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] name: String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]] package_dimensions: Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: `height`,`length`,`width` and `weight`; the precision is 2 decimal places.
        :param pulumi.Input[_builtins.str] product_id: String. The bespoke unique identifier for the object.
        :param pulumi.Input[_builtins.bool] shippable: Bool. Whether this product is shipped (i.e., physical goods).
        :param pulumi.Input[_builtins.str] statement_descriptor: String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`,` >`, `\\`, `"`, `’` characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
        :param pulumi.Input[_builtins.str] tax_code: String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
        :param pulumi.Input[_builtins.str] unit_label: String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
        :param pulumi.Input[_builtins.str] url: String. A URL of a publicly-accessible webpage for this product.
        """
        if active is not None:
            pulumi.set(__self__, "active", active)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if images is not None:
            pulumi.set(__self__, "images", images)
        if marketing_features is not None:
            pulumi.set(__self__, "marketing_features", marketing_features)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if package_dimensions is not None:
            pulumi.set(__self__, "package_dimensions", package_dimensions)
        if product_id is not None:
            pulumi.set(__self__, "product_id", product_id)
        if shippable is not None:
            pulumi.set(__self__, "shippable", shippable)
        if statement_descriptor is not None:
            pulumi.set(__self__, "statement_descriptor", statement_descriptor)
        if tax_code is not None:
            pulumi.set(__self__, "tax_code", tax_code)
        if unit_label is not None:
            pulumi.set(__self__, "unit_label", unit_label)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def active(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Whether the product is currently available for purchase. Defaults to `true`.
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def images(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        """
        return pulumi.get(self, "images")

    @images.setter
    def images(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "images", value)

    @_builtins.property
    @pulumi.getter(name="marketingFeatures")
    def marketing_features(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
        """
        return pulumi.get(self, "marketing_features")

    @marketing_features.setter
    def marketing_features(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "marketing_features", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="packageDimensions")
    def package_dimensions(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]]:
        """
        Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: `height`,`length`,`width` and `weight`; the precision is 2 decimal places.
        """
        return pulumi.get(self, "package_dimensions")

    @package_dimensions.setter
    def package_dimensions(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "package_dimensions", value)

    @_builtins.property
    @pulumi.getter(name="productId")
    def product_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The bespoke unique identifier for the object.
        """
        return pulumi.get(self, "product_id")

    @product_id.setter
    def product_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "product_id", value)

    @_builtins.property
    @pulumi.getter
    def shippable(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Whether this product is shipped (i.e., physical goods).
        """
        return pulumi.get(self, "shippable")

    @shippable.setter
    def shippable(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "shippable", value)

    @_builtins.property
    @pulumi.getter(name="statementDescriptor")
    def statement_descriptor(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`,` >`, `\\`, `"`, `’` characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
        """
        return pulumi.get(self, "statement_descriptor")

    @statement_descriptor.setter
    def statement_descriptor(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "statement_descriptor", value)

    @_builtins.property
    @pulumi.getter(name="taxCode")
    def tax_code(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
        """
        return pulumi.get(self, "tax_code")

    @tax_code.setter
    def tax_code(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tax_code", value)

    @_builtins.property
    @pulumi.getter(name="unitLabel")
    def unit_label(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
        """
        return pulumi.get(self, "unit_label")

    @unit_label.setter
    def unit_label(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "unit_label", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. A URL of a publicly-accessible webpage for this product.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


@pulumi.type_token("stripe:index/product:Product")
class Product(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 images: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 marketing_features: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 package_dimensions: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]] = None,
                 product_id: Optional[pulumi.Input[_builtins.str]] = None,
                 shippable: Optional[pulumi.Input[_builtins.bool]] = None,
                 statement_descriptor: Optional[pulumi.Input[_builtins.str]] = None,
                 tax_code: Optional[pulumi.Input[_builtins.str]] = None,
                 unit_label: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        With this resource, you can create a product - [Stripe API product documentation](https://stripe.com/docs/api/products).

        Products describe the specific goods or services you offer to your customers. For example,
        you might offer a Standard and Premium version of your goods or service; each version would be a separate Product.

        > Deleting a product is only possible if it has no prices associated with it.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_stripe as stripe

        # The product with more fields filled
        product = stripe.Product("product",
            description="fantastic product",
            unit_label="piece",
            url="https://www.terraform.io")
        ```

        ## Import

        ```sh
        $ pulumi import stripe:index/product:Product product <product_id>
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: Bool. Whether the product is currently available for purchase. Defaults to `true`.
        :param pulumi.Input[_builtins.str] description: String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] images: List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] marketing_features: List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] name: String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]] package_dimensions: Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: `height`,`length`,`width` and `weight`; the precision is 2 decimal places.
        :param pulumi.Input[_builtins.str] product_id: String. The bespoke unique identifier for the object.
        :param pulumi.Input[_builtins.bool] shippable: Bool. Whether this product is shipped (i.e., physical goods).
        :param pulumi.Input[_builtins.str] statement_descriptor: String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`,` >`, `\\`, `"`, `’` characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
        :param pulumi.Input[_builtins.str] tax_code: String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
        :param pulumi.Input[_builtins.str] unit_label: String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
        :param pulumi.Input[_builtins.str] url: String. A URL of a publicly-accessible webpage for this product.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProductArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        With this resource, you can create a product - [Stripe API product documentation](https://stripe.com/docs/api/products).

        Products describe the specific goods or services you offer to your customers. For example,
        you might offer a Standard and Premium version of your goods or service; each version would be a separate Product.

        > Deleting a product is only possible if it has no prices associated with it.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_stripe as stripe

        # The product with more fields filled
        product = stripe.Product("product",
            description="fantastic product",
            unit_label="piece",
            url="https://www.terraform.io")
        ```

        ## Import

        ```sh
        $ pulumi import stripe:index/product:Product product <product_id>
        ```

        :param str resource_name: The name of the resource.
        :param ProductArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProductArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 images: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 marketing_features: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 package_dimensions: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]] = None,
                 product_id: Optional[pulumi.Input[_builtins.str]] = None,
                 shippable: Optional[pulumi.Input[_builtins.bool]] = None,
                 statement_descriptor: Optional[pulumi.Input[_builtins.str]] = None,
                 tax_code: Optional[pulumi.Input[_builtins.str]] = None,
                 unit_label: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProductArgs.__new__(ProductArgs)

            __props__.__dict__["active"] = active
            __props__.__dict__["description"] = description
            __props__.__dict__["images"] = images
            __props__.__dict__["marketing_features"] = marketing_features
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["name"] = name
            __props__.__dict__["package_dimensions"] = package_dimensions
            __props__.__dict__["product_id"] = product_id
            __props__.__dict__["shippable"] = shippable
            __props__.__dict__["statement_descriptor"] = statement_descriptor
            __props__.__dict__["tax_code"] = tax_code
            __props__.__dict__["unit_label"] = unit_label
            __props__.__dict__["url"] = url
        super(Product, __self__).__init__(
            'stripe:index/product:Product',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            active: Optional[pulumi.Input[_builtins.bool]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            images: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            marketing_features: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            package_dimensions: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]]] = None,
            product_id: Optional[pulumi.Input[_builtins.str]] = None,
            shippable: Optional[pulumi.Input[_builtins.bool]] = None,
            statement_descriptor: Optional[pulumi.Input[_builtins.str]] = None,
            tax_code: Optional[pulumi.Input[_builtins.str]] = None,
            unit_label: Optional[pulumi.Input[_builtins.str]] = None,
            url: Optional[pulumi.Input[_builtins.str]] = None) -> 'Product':
        """
        Get an existing Product resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: Bool. Whether the product is currently available for purchase. Defaults to `true`.
        :param pulumi.Input[_builtins.str] description: String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] images: List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] marketing_features: List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] name: String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.float]]] package_dimensions: Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: `height`,`length`,`width` and `weight`; the precision is 2 decimal places.
        :param pulumi.Input[_builtins.str] product_id: String. The bespoke unique identifier for the object.
        :param pulumi.Input[_builtins.bool] shippable: Bool. Whether this product is shipped (i.e., physical goods).
        :param pulumi.Input[_builtins.str] statement_descriptor: String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`,` >`, `\\`, `"`, `’` characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
        :param pulumi.Input[_builtins.str] tax_code: String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
        :param pulumi.Input[_builtins.str] unit_label: String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
        :param pulumi.Input[_builtins.str] url: String. A URL of a publicly-accessible webpage for this product.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProductState.__new__(_ProductState)

        __props__.__dict__["active"] = active
        __props__.__dict__["description"] = description
        __props__.__dict__["images"] = images
        __props__.__dict__["marketing_features"] = marketing_features
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["name"] = name
        __props__.__dict__["package_dimensions"] = package_dimensions
        __props__.__dict__["product_id"] = product_id
        __props__.__dict__["shippable"] = shippable
        __props__.__dict__["statement_descriptor"] = statement_descriptor
        __props__.__dict__["tax_code"] = tax_code
        __props__.__dict__["unit_label"] = unit_label
        __props__.__dict__["url"] = url
        return Product(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Bool. Whether the product is currently available for purchase. Defaults to `true`.
        """
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def images(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        """
        return pulumi.get(self, "images")

    @_builtins.property
    @pulumi.getter(name="marketingFeatures")
    def marketing_features(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
        """
        return pulumi.get(self, "marketing_features")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="packageDimensions")
    def package_dimensions(self) -> pulumi.Output[Optional[Mapping[str, _builtins.float]]]:
        """
        Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: `height`,`length`,`width` and `weight`; the precision is 2 decimal places.
        """
        return pulumi.get(self, "package_dimensions")

    @_builtins.property
    @pulumi.getter(name="productId")
    def product_id(self) -> pulumi.Output[_builtins.str]:
        """
        String. The bespoke unique identifier for the object.
        """
        return pulumi.get(self, "product_id")

    @_builtins.property
    @pulumi.getter
    def shippable(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Bool. Whether this product is shipped (i.e., physical goods).
        """
        return pulumi.get(self, "shippable")

    @_builtins.property
    @pulumi.getter(name="statementDescriptor")
    def statement_descriptor(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`,` >`, `\\`, `"`, `’` characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
        """
        return pulumi.get(self, "statement_descriptor")

    @_builtins.property
    @pulumi.getter(name="taxCode")
    def tax_code(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
        """
        return pulumi.get(self, "tax_code")

    @_builtins.property
    @pulumi.getter(name="unitLabel")
    def unit_label(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
        """
        return pulumi.get(self, "unit_label")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. A URL of a publicly-accessible webpage for this product.
        """
        return pulumi.get(self, "url")

