# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['TaxRateArgs', 'TaxRate']

@pulumi.input_type
class TaxRateArgs:
    def __init__(__self__, *,
                 display_name: pulumi.Input[_builtins.str],
                 inclusive: pulumi.Input[_builtins.bool],
                 percentage: pulumi.Input[_builtins.float],
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 jurisdiction: Optional[pulumi.Input[_builtins.str]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 tax_type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a TaxRate resource.
        :param pulumi.Input[_builtins.str] display_name: String. The display name of the tax rate, which will be shown to users.
        :param pulumi.Input[_builtins.bool] inclusive: Bool. This specifies if the tax rate is inclusive or exclusive.
               * `percentage ` - (Required) Float. This represents the tax rate percent out of 100.
        :param pulumi.Input[_builtins.float] percentage: This represents the tax rate percent out of 100.
        :param pulumi.Input[_builtins.bool] active: Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
        :param pulumi.Input[_builtins.str] country: String. Two-letter country code (ISO 3166-1 alpha-2).
        :param pulumi.Input[_builtins.str] description: String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
        :param pulumi.Input[_builtins.str] jurisdiction: String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
        :param pulumi.Input[_builtins.str] state: String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
        :param pulumi.Input[_builtins.str] tax_type: String. The high-level tax type, such as vat or sales_tax.
        """
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "inclusive", inclusive)
        pulumi.set(__self__, "percentage", percentage)
        if active is not None:
            pulumi.set(__self__, "active", active)
        if country is not None:
            pulumi.set(__self__, "country", country)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if jurisdiction is not None:
            pulumi.set(__self__, "jurisdiction", jurisdiction)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if tax_type is not None:
            pulumi.set(__self__, "tax_type", tax_type)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str]:
        """
        String. The display name of the tax rate, which will be shown to users.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def inclusive(self) -> pulumi.Input[_builtins.bool]:
        """
        Bool. This specifies if the tax rate is inclusive or exclusive.
        * `percentage ` - (Required) Float. This represents the tax rate percent out of 100.
        """
        return pulumi.get(self, "inclusive")

    @inclusive.setter
    def inclusive(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "inclusive", value)

    @_builtins.property
    @pulumi.getter
    def percentage(self) -> pulumi.Input[_builtins.float]:
        """
        This represents the tax rate percent out of 100.
        """
        return pulumi.get(self, "percentage")

    @percentage.setter
    def percentage(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "percentage", value)

    @_builtins.property
    @pulumi.getter
    def active(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def country(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. Two-letter country code (ISO 3166-1 alpha-2).
        """
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "country", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def jurisdiction(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
        """
        return pulumi.get(self, "jurisdiction")

    @jurisdiction.setter
    def jurisdiction(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jurisdiction", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter(name="taxType")
    def tax_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The high-level tax type, such as vat or sales_tax.
        """
        return pulumi.get(self, "tax_type")

    @tax_type.setter
    def tax_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tax_type", value)


@pulumi.input_type
class _TaxRateState:
    def __init__(__self__, *,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 created: Optional[pulumi.Input[_builtins.int]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 inclusive: Optional[pulumi.Input[_builtins.bool]] = None,
                 jurisdiction: Optional[pulumi.Input[_builtins.str]] = None,
                 livemode: Optional[pulumi.Input[_builtins.bool]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 object: Optional[pulumi.Input[_builtins.str]] = None,
                 percentage: Optional[pulumi.Input[_builtins.float]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 tax_type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering TaxRate resources.
        :param pulumi.Input[_builtins.bool] active: Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
        :param pulumi.Input[_builtins.str] country: String. Two-letter country code (ISO 3166-1 alpha-2).
        :param pulumi.Input[_builtins.int] created: Int. Time at which the object was created. Measured in seconds since the Unix epoch.
        :param pulumi.Input[_builtins.str] description: String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
        :param pulumi.Input[_builtins.str] display_name: String. The display name of the tax rate, which will be shown to users.
        :param pulumi.Input[_builtins.bool] inclusive: Bool. This specifies if the tax rate is inclusive or exclusive.
               * `percentage ` - (Required) Float. This represents the tax rate percent out of 100.
        :param pulumi.Input[_builtins.str] jurisdiction: String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
        :param pulumi.Input[_builtins.bool] livemode: Bool. Has the value true if the object exists in live mode or the value false if the object exists in test mode.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
        :param pulumi.Input[_builtins.str] object: String. String representing the object’s type. Objects of the same type share the same value.
        :param pulumi.Input[_builtins.float] percentage: This represents the tax rate percent out of 100.
        :param pulumi.Input[_builtins.str] state: String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
        :param pulumi.Input[_builtins.str] tax_type: String. The high-level tax type, such as vat or sales_tax.
        """
        if active is not None:
            pulumi.set(__self__, "active", active)
        if country is not None:
            pulumi.set(__self__, "country", country)
        if created is not None:
            pulumi.set(__self__, "created", created)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if inclusive is not None:
            pulumi.set(__self__, "inclusive", inclusive)
        if jurisdiction is not None:
            pulumi.set(__self__, "jurisdiction", jurisdiction)
        if livemode is not None:
            pulumi.set(__self__, "livemode", livemode)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if object is not None:
            pulumi.set(__self__, "object", object)
        if percentage is not None:
            pulumi.set(__self__, "percentage", percentage)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if tax_type is not None:
            pulumi.set(__self__, "tax_type", tax_type)

    @_builtins.property
    @pulumi.getter
    def active(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def country(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. Two-letter country code (ISO 3166-1 alpha-2).
        """
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "country", value)

    @_builtins.property
    @pulumi.getter
    def created(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Int. Time at which the object was created. Measured in seconds since the Unix epoch.
        """
        return pulumi.get(self, "created")

    @created.setter
    def created(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "created", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The display name of the tax rate, which will be shown to users.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def inclusive(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. This specifies if the tax rate is inclusive or exclusive.
        * `percentage ` - (Required) Float. This represents the tax rate percent out of 100.
        """
        return pulumi.get(self, "inclusive")

    @inclusive.setter
    def inclusive(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "inclusive", value)

    @_builtins.property
    @pulumi.getter
    def jurisdiction(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
        """
        return pulumi.get(self, "jurisdiction")

    @jurisdiction.setter
    def jurisdiction(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jurisdiction", value)

    @_builtins.property
    @pulumi.getter
    def livemode(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Has the value true if the object exists in live mode or the value false if the object exists in test mode.
        """
        return pulumi.get(self, "livemode")

    @livemode.setter
    def livemode(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "livemode", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def object(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. String representing the object’s type. Objects of the same type share the same value.
        """
        return pulumi.get(self, "object")

    @object.setter
    def object(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "object", value)

    @_builtins.property
    @pulumi.getter
    def percentage(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        This represents the tax rate percent out of 100.
        """
        return pulumi.get(self, "percentage")

    @percentage.setter
    def percentage(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "percentage", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter(name="taxType")
    def tax_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The high-level tax type, such as vat or sales_tax.
        """
        return pulumi.get(self, "tax_type")

    @tax_type.setter
    def tax_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tax_type", value)


@pulumi.type_token("stripe:index/taxRate:TaxRate")
class TaxRate(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 inclusive: Optional[pulumi.Input[_builtins.bool]] = None,
                 jurisdiction: Optional[pulumi.Input[_builtins.str]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 percentage: Optional[pulumi.Input[_builtins.float]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 tax_type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        With this resource, you can create a tax rate - [Stripe API tax rate  documentation](https://stripe.com/docs/api/tax_rates).

        Tax rates can be applied to invoices, subscriptions and Checkout Sessions to collect tax.

        > Removal of the tax rate isn't supported through the Stripe API.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_stripe as stripe

        tax_rate = stripe.TaxRate("taxRate",
            active=True,
            country="AU",
            description="GST Australia",
            display_name="GST",
            inclusive=True,
            jurisdiction="AU",
            metadata={},
            percentage=10,
            state="",
            tax_type="")
        ```

        ## Import

        ```sh
        $ pulumi import stripe:index/taxRate:TaxRate rate <tax_rate_id>
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
        :param pulumi.Input[_builtins.str] country: String. Two-letter country code (ISO 3166-1 alpha-2).
        :param pulumi.Input[_builtins.str] description: String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
        :param pulumi.Input[_builtins.str] display_name: String. The display name of the tax rate, which will be shown to users.
        :param pulumi.Input[_builtins.bool] inclusive: Bool. This specifies if the tax rate is inclusive or exclusive.
               * `percentage ` - (Required) Float. This represents the tax rate percent out of 100.
        :param pulumi.Input[_builtins.str] jurisdiction: String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
        :param pulumi.Input[_builtins.float] percentage: This represents the tax rate percent out of 100.
        :param pulumi.Input[_builtins.str] state: String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
        :param pulumi.Input[_builtins.str] tax_type: String. The high-level tax type, such as vat or sales_tax.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TaxRateArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        With this resource, you can create a tax rate - [Stripe API tax rate  documentation](https://stripe.com/docs/api/tax_rates).

        Tax rates can be applied to invoices, subscriptions and Checkout Sessions to collect tax.

        > Removal of the tax rate isn't supported through the Stripe API.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_stripe as stripe

        tax_rate = stripe.TaxRate("taxRate",
            active=True,
            country="AU",
            description="GST Australia",
            display_name="GST",
            inclusive=True,
            jurisdiction="AU",
            metadata={},
            percentage=10,
            state="",
            tax_type="")
        ```

        ## Import

        ```sh
        $ pulumi import stripe:index/taxRate:TaxRate rate <tax_rate_id>
        ```

        :param str resource_name: The name of the resource.
        :param TaxRateArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TaxRateArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 inclusive: Optional[pulumi.Input[_builtins.bool]] = None,
                 jurisdiction: Optional[pulumi.Input[_builtins.str]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 percentage: Optional[pulumi.Input[_builtins.float]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 tax_type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TaxRateArgs.__new__(TaxRateArgs)

            __props__.__dict__["active"] = active
            __props__.__dict__["country"] = country
            __props__.__dict__["description"] = description
            if display_name is None and not opts.urn:
                raise TypeError("Missing required property 'display_name'")
            __props__.__dict__["display_name"] = display_name
            if inclusive is None and not opts.urn:
                raise TypeError("Missing required property 'inclusive'")
            __props__.__dict__["inclusive"] = inclusive
            __props__.__dict__["jurisdiction"] = jurisdiction
            __props__.__dict__["metadata"] = metadata
            if percentage is None and not opts.urn:
                raise TypeError("Missing required property 'percentage'")
            __props__.__dict__["percentage"] = percentage
            __props__.__dict__["state"] = state
            __props__.__dict__["tax_type"] = tax_type
            __props__.__dict__["created"] = None
            __props__.__dict__["livemode"] = None
            __props__.__dict__["object"] = None
        super(TaxRate, __self__).__init__(
            'stripe:index/taxRate:TaxRate',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            active: Optional[pulumi.Input[_builtins.bool]] = None,
            country: Optional[pulumi.Input[_builtins.str]] = None,
            created: Optional[pulumi.Input[_builtins.int]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            display_name: Optional[pulumi.Input[_builtins.str]] = None,
            inclusive: Optional[pulumi.Input[_builtins.bool]] = None,
            jurisdiction: Optional[pulumi.Input[_builtins.str]] = None,
            livemode: Optional[pulumi.Input[_builtins.bool]] = None,
            metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            object: Optional[pulumi.Input[_builtins.str]] = None,
            percentage: Optional[pulumi.Input[_builtins.float]] = None,
            state: Optional[pulumi.Input[_builtins.str]] = None,
            tax_type: Optional[pulumi.Input[_builtins.str]] = None) -> 'TaxRate':
        """
        Get an existing TaxRate resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
        :param pulumi.Input[_builtins.str] country: String. Two-letter country code (ISO 3166-1 alpha-2).
        :param pulumi.Input[_builtins.int] created: Int. Time at which the object was created. Measured in seconds since the Unix epoch.
        :param pulumi.Input[_builtins.str] description: String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
        :param pulumi.Input[_builtins.str] display_name: String. The display name of the tax rate, which will be shown to users.
        :param pulumi.Input[_builtins.bool] inclusive: Bool. This specifies if the tax rate is inclusive or exclusive.
               * `percentage ` - (Required) Float. This represents the tax rate percent out of 100.
        :param pulumi.Input[_builtins.str] jurisdiction: String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
        :param pulumi.Input[_builtins.bool] livemode: Bool. Has the value true if the object exists in live mode or the value false if the object exists in test mode.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
        :param pulumi.Input[_builtins.str] object: String. String representing the object’s type. Objects of the same type share the same value.
        :param pulumi.Input[_builtins.float] percentage: This represents the tax rate percent out of 100.
        :param pulumi.Input[_builtins.str] state: String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
        :param pulumi.Input[_builtins.str] tax_type: String. The high-level tax type, such as vat or sales_tax.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _TaxRateState.__new__(_TaxRateState)

        __props__.__dict__["active"] = active
        __props__.__dict__["country"] = country
        __props__.__dict__["created"] = created
        __props__.__dict__["description"] = description
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["inclusive"] = inclusive
        __props__.__dict__["jurisdiction"] = jurisdiction
        __props__.__dict__["livemode"] = livemode
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["object"] = object
        __props__.__dict__["percentage"] = percentage
        __props__.__dict__["state"] = state
        __props__.__dict__["tax_type"] = tax_type
        return TaxRate(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
        """
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter
    def country(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. Two-letter country code (ISO 3166-1 alpha-2).
        """
        return pulumi.get(self, "country")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.int]:
        """
        Int. Time at which the object was created. Measured in seconds since the Unix epoch.
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[_builtins.str]:
        """
        String. The display name of the tax rate, which will be shown to users.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def inclusive(self) -> pulumi.Output[_builtins.bool]:
        """
        Bool. This specifies if the tax rate is inclusive or exclusive.
        * `percentage ` - (Required) Float. This represents the tax rate percent out of 100.
        """
        return pulumi.get(self, "inclusive")

    @_builtins.property
    @pulumi.getter
    def jurisdiction(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
        """
        return pulumi.get(self, "jurisdiction")

    @_builtins.property
    @pulumi.getter
    def livemode(self) -> pulumi.Output[_builtins.bool]:
        """
        Bool. Has the value true if the object exists in live mode or the value false if the object exists in test mode.
        """
        return pulumi.get(self, "livemode")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def object(self) -> pulumi.Output[_builtins.str]:
        """
        String. String representing the object’s type. Objects of the same type share the same value.
        """
        return pulumi.get(self, "object")

    @_builtins.property
    @pulumi.getter
    def percentage(self) -> pulumi.Output[_builtins.float]:
        """
        This represents the tax rate percent out of 100.
        """
        return pulumi.get(self, "percentage")

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter(name="taxType")
    def tax_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. The high-level tax type, such as vat or sales_tax.
        """
        return pulumi.get(self, "tax_type")

