# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WebhookEndpointArgs', 'WebhookEndpoint']

@pulumi.input_type
class WebhookEndpointArgs:
    def __init__(__self__, *,
                 enabled_events: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 url: pulumi.Input[_builtins.str],
                 api_version: Optional[pulumi.Input[_builtins.str]] = None,
                 connect: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a WebhookEndpoint resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] enabled_events: List(String). The list of events to enable for this endpoint. `[*]` indicates that all events are enabled, except those that require explicit selection. All supported events listed here: [Stripe event types](https://stripe.com/docs/api/events/types).
        :param pulumi.Input[_builtins.str] url: String. The URL of the webhook endpoint.
        :param pulumi.Input[_builtins.str] api_version: String. Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe Version.
        :param pulumi.Input[_builtins.bool] connect: Bool. Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.
        :param pulumi.Input[_builtins.str] description: String. Description of what the webhook is used for.
        :param pulumi.Input[_builtins.bool] disabled: Bool. Disable the webhook endpoint if set to `true`. Can be used only for modification already existing webhook endpoint.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        pulumi.set(__self__, "enabled_events", enabled_events)
        pulumi.set(__self__, "url", url)
        if api_version is not None:
            pulumi.set(__self__, "api_version", api_version)
        if connect is not None:
            pulumi.set(__self__, "connect", connect)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)

    @_builtins.property
    @pulumi.getter(name="enabledEvents")
    def enabled_events(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        List(String). The list of events to enable for this endpoint. `[*]` indicates that all events are enabled, except those that require explicit selection. All supported events listed here: [Stripe event types](https://stripe.com/docs/api/events/types).
        """
        return pulumi.get(self, "enabled_events")

    @enabled_events.setter
    def enabled_events(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "enabled_events", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Input[_builtins.str]:
        """
        String. The URL of the webhook endpoint.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe Version.
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def connect(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.
        """
        return pulumi.get(self, "connect")

    @connect.setter
    def connect(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "connect", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. Description of what the webhook is used for.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Disable the webhook endpoint if set to `true`. Can be used only for modification already existing webhook endpoint.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)


@pulumi.input_type
class _WebhookEndpointState:
    def __init__(__self__, *,
                 api_version: Optional[pulumi.Input[_builtins.str]] = None,
                 application: Optional[pulumi.Input[_builtins.str]] = None,
                 connect: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 enabled_events: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 secret: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering WebhookEndpoint resources.
        :param pulumi.Input[_builtins.str] api_version: String. Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe Version.
        :param pulumi.Input[_builtins.str] application: String. The ID of the associated Connect application.
        :param pulumi.Input[_builtins.bool] connect: Bool. Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.
        :param pulumi.Input[_builtins.str] description: String. Description of what the webhook is used for.
        :param pulumi.Input[_builtins.bool] disabled: Bool. Disable the webhook endpoint if set to `true`. Can be used only for modification already existing webhook endpoint.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] enabled_events: List(String). The list of events to enable for this endpoint. `[*]` indicates that all events are enabled, except those that require explicit selection. All supported events listed here: [Stripe event types](https://stripe.com/docs/api/events/types).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] secret: String. The endpoint’s secret, used to generate webhook signatures. This field is marked as `sensitive`.
        :param pulumi.Input[_builtins.str] url: String. The URL of the webhook endpoint.
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", api_version)
        if application is not None:
            pulumi.set(__self__, "application", application)
        if connect is not None:
            pulumi.set(__self__, "connect", connect)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if enabled_events is not None:
            pulumi.set(__self__, "enabled_events", enabled_events)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe Version.
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def application(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The ID of the associated Connect application.
        """
        return pulumi.get(self, "application")

    @application.setter
    def application(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "application", value)

    @_builtins.property
    @pulumi.getter
    def connect(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.
        """
        return pulumi.get(self, "connect")

    @connect.setter
    def connect(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "connect", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. Description of what the webhook is used for.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Bool. Disable the webhook endpoint if set to `true`. Can be used only for modification already existing webhook endpoint.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter(name="enabledEvents")
    def enabled_events(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List(String). The list of events to enable for this endpoint. `[*]` indicates that all events are enabled, except those that require explicit selection. All supported events listed here: [Stripe event types](https://stripe.com/docs/api/events/types).
        """
        return pulumi.get(self, "enabled_events")

    @enabled_events.setter
    def enabled_events(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "enabled_events", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The endpoint’s secret, used to generate webhook signatures. This field is marked as `sensitive`.
        """
        return pulumi.get(self, "secret")

    @secret.setter
    def secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secret", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        String. The URL of the webhook endpoint.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


@pulumi.type_token("stripe:index/webhookEndpoint:WebhookEndpoint")
class WebhookEndpoint(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: Optional[pulumi.Input[_builtins.str]] = None,
                 connect: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 enabled_events: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        With this resource, you can create a webhook endpoint - [Stripe API webhook endpoint documentation](https://stripe.com/docs/api/webhook_endpoints).

        You can configure webhook endpoints via the API to be notified about events that happen in your Stripe account or connected accounts.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_stripe as stripe

        webhook = stripe.WebhookEndpoint("webhook",
            description="example of webhook",
            enabled_events=[
                "customer.subscription.created",
                "customer.subscription.updated",
            ],
            url="https://webhook-url-consumer.com")
        ```

        ## Import

        ```sh
        $ pulumi import stripe:index/webhookEndpoint:WebhookEndpoint webhook <webhook_endpoint_id>
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_version: String. Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe Version.
        :param pulumi.Input[_builtins.bool] connect: Bool. Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.
        :param pulumi.Input[_builtins.str] description: String. Description of what the webhook is used for.
        :param pulumi.Input[_builtins.bool] disabled: Bool. Disable the webhook endpoint if set to `true`. Can be used only for modification already existing webhook endpoint.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] enabled_events: List(String). The list of events to enable for this endpoint. `[*]` indicates that all events are enabled, except those that require explicit selection. All supported events listed here: [Stripe event types](https://stripe.com/docs/api/events/types).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] url: String. The URL of the webhook endpoint.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: WebhookEndpointArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        With this resource, you can create a webhook endpoint - [Stripe API webhook endpoint documentation](https://stripe.com/docs/api/webhook_endpoints).

        You can configure webhook endpoints via the API to be notified about events that happen in your Stripe account or connected accounts.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_stripe as stripe

        webhook = stripe.WebhookEndpoint("webhook",
            description="example of webhook",
            enabled_events=[
                "customer.subscription.created",
                "customer.subscription.updated",
            ],
            url="https://webhook-url-consumer.com")
        ```

        ## Import

        ```sh
        $ pulumi import stripe:index/webhookEndpoint:WebhookEndpoint webhook <webhook_endpoint_id>
        ```

        :param str resource_name: The name of the resource.
        :param WebhookEndpointArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WebhookEndpointArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: Optional[pulumi.Input[_builtins.str]] = None,
                 connect: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 enabled_events: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WebhookEndpointArgs.__new__(WebhookEndpointArgs)

            __props__.__dict__["api_version"] = api_version
            __props__.__dict__["connect"] = connect
            __props__.__dict__["description"] = description
            __props__.__dict__["disabled"] = disabled
            if enabled_events is None and not opts.urn:
                raise TypeError("Missing required property 'enabled_events'")
            __props__.__dict__["enabled_events"] = enabled_events
            __props__.__dict__["metadata"] = metadata
            if url is None and not opts.urn:
                raise TypeError("Missing required property 'url'")
            __props__.__dict__["url"] = url
            __props__.__dict__["application"] = None
            __props__.__dict__["secret"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["secret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(WebhookEndpoint, __self__).__init__(
            'stripe:index/webhookEndpoint:WebhookEndpoint',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            api_version: Optional[pulumi.Input[_builtins.str]] = None,
            application: Optional[pulumi.Input[_builtins.str]] = None,
            connect: Optional[pulumi.Input[_builtins.bool]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            disabled: Optional[pulumi.Input[_builtins.bool]] = None,
            enabled_events: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            secret: Optional[pulumi.Input[_builtins.str]] = None,
            url: Optional[pulumi.Input[_builtins.str]] = None) -> 'WebhookEndpoint':
        """
        Get an existing WebhookEndpoint resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_version: String. Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe Version.
        :param pulumi.Input[_builtins.str] application: String. The ID of the associated Connect application.
        :param pulumi.Input[_builtins.bool] connect: Bool. Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.
        :param pulumi.Input[_builtins.str] description: String. Description of what the webhook is used for.
        :param pulumi.Input[_builtins.bool] disabled: Bool. Disable the webhook endpoint if set to `true`. Can be used only for modification already existing webhook endpoint.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] enabled_events: List(String). The list of events to enable for this endpoint. `[*]` indicates that all events are enabled, except those that require explicit selection. All supported events listed here: [Stripe event types](https://stripe.com/docs/api/events/types).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] secret: String. The endpoint’s secret, used to generate webhook signatures. This field is marked as `sensitive`.
        :param pulumi.Input[_builtins.str] url: String. The URL of the webhook endpoint.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WebhookEndpointState.__new__(_WebhookEndpointState)

        __props__.__dict__["api_version"] = api_version
        __props__.__dict__["application"] = application
        __props__.__dict__["connect"] = connect
        __props__.__dict__["description"] = description
        __props__.__dict__["disabled"] = disabled
        __props__.__dict__["enabled_events"] = enabled_events
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["secret"] = secret
        __props__.__dict__["url"] = url
        return WebhookEndpoint(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe Version.
        """
        return pulumi.get(self, "api_version")

    @_builtins.property
    @pulumi.getter
    def application(self) -> pulumi.Output[_builtins.str]:
        """
        String. The ID of the associated Connect application.
        """
        return pulumi.get(self, "application")

    @_builtins.property
    @pulumi.getter
    def connect(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Bool. Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.
        """
        return pulumi.get(self, "connect")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        String. Description of what the webhook is used for.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Bool. Disable the webhook endpoint if set to `true`. Can be used only for modification already existing webhook endpoint.
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="enabledEvents")
    def enabled_events(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        List(String). The list of events to enable for this endpoint. `[*]` indicates that all events are enabled, except those that require explicit selection. All supported events listed here: [Stripe event types](https://stripe.com/docs/api/events/types).
        """
        return pulumi.get(self, "enabled_events")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Output[_builtins.str]:
        """
        String. The endpoint’s secret, used to generate webhook signatures. This field is marked as `sensitive`.
        """
        return pulumi.get(self, "secret")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[_builtins.str]:
        """
        String. The URL of the webhook endpoint.
        """
        return pulumi.get(self, "url")

