# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import errno
from setuptools import setup, find_packages
from setuptools.command.install import install
from subprocess import check_call


VERSION = "0.0.0"
def readme():
    try:
        with open('README.md', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return "stripe Pulumi Package - Development Version"


setup(name='pulumi_stripe',
      python_requires='>=3.9',
      version=VERSION,
      description="A Pulumi package for creating and managing Stripe resources.",
      long_description=readme(),
      long_description_content_type='text/markdown',
      keywords='pulumi stripe category/cloud',
      url='https://www.pulumi.com',
      project_urls={
          'Repository': 'https://github.com/georgegebbett/pulumi-stripe'
      },
      license='Apache-2.0',
      packages=find_packages(),
      package_data={
          'pulumi_stripe': [
              'py.typed',
              'pulumi-plugin.json',
          ]
      },
      install_requires=[
          'parver>=0.2.1',
          'pulumi>=3.0.0,<4.0.0',
          'semver>=2.8.1',
          'typing-extensions>=4.11,<5; python_version < "3.11"'
      ],
      zip_safe=False)
