// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Stripe.Outputs;


[OutputType]
public sealed class MeterDefaultAggregation
{
    /// <summary>
    /// String. Specifies how events are aggregated. Allowed values are `Count` to count the number of events and `Sum` to sum each event’s value.
    /// </summary>
    public readonly string Formula;

    [OutputConstructor]
    private MeterDefaultAggregation(string formula)
    {
        Formula = formula;
    }
}
