// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class MeterCustomerMapping
    {
        /// <summary>
        /// String. The key in the event payload to use for customer mapping.
        /// </summary>
        public readonly string EventPayloadKey;
        /// <summary>
        /// String. The method for mapping a meter event to a customer. Must be `ById`.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private MeterCustomerMapping(
            string eventPayloadKey,

            string type)
        {
            EventPayloadKey = eventPayloadKey;
            Type = type;
        }
    }
}
