// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Stripe.Outputs;


[OutputType]
public sealed class PortalConfigurationFeaturesPaymentMethodUpdate
{
    /// <summary>
    /// Whether the feature is enabled.
    /// </summary>
    public readonly bool Enabled;

    [OutputConstructor]
    private PortalConfigurationFeaturesPaymentMethodUpdate(bool enabled)
    {
        Enabled = enabled;
    }
}
