// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Stripe.Outputs;


[OutputType]
public sealed class PortalConfigurationFeaturesSubscriptionCancelCancellationReason
{
    /// <summary>
    /// Bool. Whether the feature is enabled.
    /// </summary>
    public readonly bool Enabled;
    /// <summary>
    /// List(String). Which cancellation reasons will be given as options to the customer. Supported values are `TooExpensive`, `MissingFeatures`, `SwitchedService`, `Unused`, `CustomerService`, `TooComplex`, `LowQuality`, and `Other`.
    /// </summary>
    public readonly ImmutableArray<string> Options;

    [OutputConstructor]
    private PortalConfigurationFeaturesSubscriptionCancelCancellationReason(
        bool enabled,

        ImmutableArray<string> options)
    {
        Enabled = enabled;
        Options = options;
    }
}
