// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PortalConfigurationFeaturesCustomerUpdateGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowedUpdates")]
        private InputList<string>? _allowedUpdates;

        /// <summary>
        /// The types of customer updates that are supported. When empty, customers are not updatable.
        /// </summary>
        public InputList<string> AllowedUpdates
        {
            get => _allowedUpdates ?? (_allowedUpdates = new InputList<string>());
            set => _allowedUpdates = value;
        }

        /// <summary>
        /// Whether the feature is enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        public PortalConfigurationFeaturesCustomerUpdateGetArgs()
        {
        }
        public static new PortalConfigurationFeaturesCustomerUpdateGetArgs Empty => new PortalConfigurationFeaturesCustomerUpdateGetArgs();
    }
}
