// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Stripe.Inputs;


public sealed class PortalConfigurationBusinessProfileGetArgs : global::Pulumi.ResourceArgs
{
    /// <summary>
    /// String. The messaging shown to customers in the portal.
    /// </summary>
    [Input("headline")]
    public Input<string>? Headline { get; set; }

    /// <summary>
    /// String. A link to the business's publicly available privacy policy.
    /// </summary>
    [Input("privacyPolicyUrl")]
    public Input<string>? PrivacyPolicyUrl { get; set; }

    /// <summary>
    /// String. A link to the business's publicly available terms of service.
    /// </summary>
    [Input("termsOfServiceUrl")]
    public Input<string>? TermsOfServiceUrl { get; set; }

    public PortalConfigurationBusinessProfileGetArgs()
    {
    }
    public static new PortalConfigurationBusinessProfileGetArgs Empty => new();
}
