// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PriceTransformQuantityArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Int. Divide usage by this number.
        /// </summary>
        [Input("divideBy", required: true)]
        public Input<int> DivideBy { get; set; } = null!;

        /// <summary>
        /// String. After division, either round the result `Up` or `Down`.
        /// </summary>
        [Input("round", required: true)]
        public Input<string> Round { get; set; } = null!;

        public PriceTransformQuantityArgs()
        {
        }
        public static new PriceTransformQuantityArgs Empty => new PriceTransformQuantityArgs();
    }
}
