// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Stripe.Inputs;


public sealed class ShippingRateFixedAmountArgs : global::Pulumi.ResourceArgs
{
    /// <summary>
    /// Int. A non-negative integer in cents representing how much to charge.
    /// </summary>
    [Input("amount", required: true)]
    public Input<int> Amount { get; set; } = null!;

    /// <summary>
    /// String. Three-letter ISO currency code, in lowercase - [supported currencies](https://stripe.com/docs/currencies).
    /// </summary>
    [Input("currency", required: true)]
    public Input<string> Currency { get; set; } = null!;

    [Input("currencyOptions")]
    private InputList<Inputs.ShippingRateFixedAmountCurrencyOptionArgs>? _currencyOptions;

    /// <summary>
    /// List(Resource). Please see argument details Currency Option
    /// </summary>
    public InputList<Inputs.ShippingRateFixedAmountCurrencyOptionArgs> CurrencyOptions
    {
        get => _currencyOptions ??= [];
        set => _currencyOptions = value;
    }

    public ShippingRateFixedAmountArgs()
    {
    }
    public static new ShippingRateFixedAmountArgs Empty => new();
}
